version: '3.8'

services:
  erp-lumark:
    build: 
      context: .
      target: dev
    container_name: erp-lumark-app
    restart: always
    ports:
      - "3003:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: ["node", "server.js"]
